version: "3"
services:
  eta:
    volumes:
    # Might want to change this to include app
      - ./app:/app
    ports:
      - "8080:8080"
#    environment:
#     - AWS_ACCESS_KEY_ID=
#     - AWS_SECRET_ACCESS_KEY=
#     - ENV=local
   #  - FLASK_ENV=development If you want to flask to reload on a code change
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
     - redis
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
     - ./data:/data
    ports:
     - "6379:6379"